
kind: pipeline
type: docker
name: test1
platform:
  os: linux
  arch: amd64
steps:
- name: golang
  image: golang
  commands:
  - go get
  - go test
trigger:
  branch:
  - master
  event:
  - push
